import { buildBannerAssets, buildFontMap, gradientCSS } from '../figmaParser.js';

const _vcTypes = new Set(['VECTOR','BOOLEAN_OPERATION','STAR','POLYGON','COMPONENT','INSTANCE','GROUP']);

export function generateReactInlineStyles(banners) {
  const sizesData = banners.map(b => {
    const layerData = b.layers.map((l, idx) => {
      const style = {
        position: 'absolute',
        boxSizing: 'border-box',
        left: l.pos?.x ?? 0,
        top: l.pos?.y ?? 0,
        width: l.size?.w ?? 0,
        height: l.size?.h ?? 0,
        zIndex: idx,
      };
      if (l.opacity !== undefined && l.opacity !== 1) style.opacity = l.opacity;
      if (l.borderRadius) style.borderRadius = l.borderRadius;
      if (l.type !== 'TEXT' && !l.hasImage) {
        if (l.gradient) style.background = gradientCSS(l.gradient);
        else if (l.fill) style.background = l.fill;
      }
      if (l.type === 'TEXT') {
        if (l.color) style.color = l.color;
        if (l.fontSize) style.fontSize = l.fontSize;
        if (l.fontWeight) style.fontWeight = l.fontWeight;
        if (l.fontFamily) style.fontFamily = `'${l.fontFamily}', sans-serif`;
        if (l.textAlign) style.textAlign = l.textAlign;
        if (l.lineHeight) style.lineHeight = `${l.lineHeight}px`;
        style.whiteSpace = 'pre-wrap';
        style.overflow = 'hidden';
        style.display = 'block';
      }
      if (l.hasImage && l.imageUrl) {
        const fit = _vcTypes.has(l.type) ? 'contain' : 'cover';
        style.backgroundImage = `url('${l.imageUrl}')`;
        style.backgroundRepeat = 'no-repeat';
        style.backgroundSize = fit;
        style.backgroundPosition = 'center';
      }
      return { name: l.name, type: l.type, text: (l.type === 'TEXT' ? l.text : ''), style };
    });
    return {
      w: b.w, h: b.h,
      background: b.rootFill || (b.rootGradient ? gradientCSS(b.rootGradient) : 'transparent'),
      layers: layerData
    };
  });

  const sizesJSON = JSON.stringify(sizesData, null, 2);

  const allFontMap = {};
  banners.forEach(b => Object.entries(buildFontMap(b.layers)).forEach(([f, ws]) => {
    if (!allFontMap[f]) allFontMap[f] = new Set();
    ws.forEach(w => allFontMap[f].add(w));
  }));
  const fontFamilies = Object.keys(allFontMap);
  const fontHref = fontFamilies.length
    ? `https://fonts.googleapis.com/css2?${fontFamilies.map(f => `family=${f.replace(/ /g, '+')}:wght@300;400;500;600;700;800;900`).join('&')}&display=swap`
    : '';

  const jsx = `import { useRef, useEffect, useState } from 'react';

/**
 * Responsive Banner Component — React + Inline Styles
 * Generated by Code Generator from Figma.
 *
 * No CSS files required. Uses ResizeObserver to detect
 * container width and switch between banner layouts.
${fontHref ? ` *\n * Add this to your <head>:\n *   <link rel="stylesheet" href="${fontHref}">` : ''}
 */

const BANNER_SIZES = ${sizesJSON};

function getActiveSize(width) {
  for (const size of BANNER_SIZES) {
    if (width >= size.w) return size;
  }
  return BANNER_SIZES[BANNER_SIZES.length - 1];
}

export default function Banner() {
  const containerRef = useRef(null);
  const [containerWidth, setContainerWidth] = useState(BANNER_SIZES[0].w);

  useEffect(() => {
    if (!containerRef.current) return;
    const ro = new ResizeObserver(([entry]) => {
      setContainerWidth(entry.contentRect.width);
    });
    ro.observe(containerRef.current);
    setContainerWidth(containerRef.current.offsetWidth);
    return () => ro.disconnect();
  }, []);

  const active = getActiveSize(containerWidth);
  const scale  = containerWidth / active.w;

  return (
    <div ref={containerRef} style={{ width: '100%', position: 'relative' }}>
      <div style={{
        position: 'relative',
        overflow: 'hidden',
        width: '100%',
        height: active.h * scale,
      }}>
        <div style={{
          position: 'absolute',
          top: 0, left: 0,
          width: active.w,
          height: active.h,
          background: active.background,
          transform: \`scale(\${scale})\`,
          transformOrigin: 'top left',
          overflow: 'hidden',
        }}>
          {active.layers.map((layer, i) =>
            layer.type === 'TEXT' ? (
              <div
                key={i}
                style={layer.style}
                dangerouslySetInnerHTML={{ __html: layer.text }}
              />
            ) : (
              <div key={i} style={layer.style} />
            )
          )}
        </div>
      </div>
    </div>
  );
}
`;

  return [
    { name: 'Banner.jsx', content: jsx },
  ];
}
