import { buildBannerAssets } from '../figmaParser.js';

const TERMS_MODAL_CSS = `
.terms-modal { display: none; position: fixed; inset: 0; z-index: 2147483647; font-family: 'Montserrat', sans-serif; }
.terms-modal.is-open { display: block; }
.terms-modal__backdrop { position: absolute; inset: 0; background: rgba(0,0,0,.55); }
.terms-modal__dialog { position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%); width: min(92vw,900px); height: min(90vh,720px); background: #FFF; border-radius: 8px; box-shadow: 0 10px 30px rgba(0,0,0,.3); overflow: hidden; display: flex; flex-direction: column; }
.terms-modal__header { display: flex; align-items: center; justify-content: space-between; padding: 12px 16px; border-bottom: 1px solid #E5E7EB; background: #FAF7F5; flex-shrink: 0; }
.terms-modal__title { font-family: 'Montserrat', sans-serif; font-size: 14px; font-weight: 700; color: #132122; margin: 0; }
.terms-modal__close { width: 32px; height: 32px; border: none; background: transparent; font-size: 24px; line-height: 1; cursor: pointer; color: #132122; padding: 0; display: flex; align-items: center; justify-content: center; border-radius: 4px; }
.terms-modal__close:hover { background: rgba(0,0,0,.06); }
.terms-modal__body { flex: 1; position: relative; min-height: 0; background: #FFF; }
.terms-modal__frame { width: 100%; height: 100%; border: 0; display: block; }`;

const TERMS_MODAL_HTML = `  <div id="terms-modal" class="terms-modal" aria-hidden="true" role="dialog" aria-modal="true" aria-labelledby="terms-modal-title">
    <div class="terms-modal__backdrop" data-terms-close></div>
    <div class="terms-modal__dialog" role="document">
      <div class="terms-modal__header">
        <h2 id="terms-modal-title" class="terms-modal__title">Terms &amp; Conditions</h2>
        <button type="button" class="terms-modal__close" aria-label="Close" data-terms-close>&#xD7;</button>
      </div>
      <div class="terms-modal__body">
        <iframe class="terms-modal__frame" title="Terms and Conditions" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
    </div>
  </div>`;

export function generateVueCSS(banners) {
  const { fontImport, baseLayerCSSFlat, containerQueriesFlat, spanCSS, layerDivs } = buildBannerAssets(banners);

  const vue = `<template>
  <div class="bc-outer">
    <div class="bc">
      <div class="bv">
${layerDivs}
      </div>
    </div>
${TERMS_MODAL_HTML}
  </div>
</template>

<script setup>
/**
 * Responsive Banner Component — Vue 3 SFC
 * Generated by Code Generator from Figma.
 */
<\/script>

<style>
${fontImport}

.bc-outer {
  container-type: inline-size;
  container-name: bco;
  width: 100%;
}

.bc {
  position: relative;
  overflow: hidden;
  width: 100%;
}

.bv {
  position: absolute;
  top: 0; left: 0;
  transform-origin: top left;
  overflow: hidden;
}

${baseLayerCSSFlat}

${containerQueriesFlat}

${spanCSS}

${TERMS_MODAL_CSS}
</style>
`;

  return [
    { name: 'Banner.vue', content: vue },
  ];
}
